import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { environment } from '../../environments/environment';
import { catchError } from 'rxjs/operators';
import { Empleado } from './empleado';
// import 'rxjs/add/operator/catch';
// import { HttpErrorInterceptor } from '../interceptors/httperrorinterceptor.service';

//const API_URL = environment.API_URL;
//const empleados = '/empleados';
 const API_URL = '../../assets';
 const empleados = '/empleados.json';
/**
 * El servicio que provee todo lo de los empleados
 */
@Injectable()
export class EmpleadoService {
  /**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) {
   }

   /**
    * Obtener todos los empleads
    */
    getEmpleados(): Observable<Empleado[]> {
    return this.http.get<Empleado[]>(API_URL + empleados);
  }

  /**
  * Returns the Observable object with the details of a empleado retrieved from the API
  * @returns The client details
  */
  getEmpleado(empleadoId): Observable<Empleado> {
    return this.http.get<Empleado>(API_URL + empleados + '/' + empleadoId).pipe(catchError(err => this.handleError(err)));
  }

  /**
  * The method which handles the errors generated by the requests
  * @param error The error which the API REST returned
  */
  private handleError(error: any) {
    return throwError(error.error.errorMessage);
  }
}
