import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Cliente } from './cliente';
import { Observable, throwError } from 'rxjs';
import { environment } from '../../environments/environment'; 
import { catchError } from 'rxjs/operators';
import { TarjetaDeCredito } from './tarjetaDeCredito';
//import 'rxjs/add/operator/catch';
//import { HttpErrorInterceptor } from '../interceptors/httperrorinterceptor.service';

const API_URL = environment.API_URL;
const clientes = '/clientes';
const tarjetas = '/tarjetas';
// const API_URL = '../../assets';
// const clientes = '/clientes.json';

/**
 * El servicio que provee todo lo de los clientes
 */
@Injectable()
export class ClienteService {

  /**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) { }
    
  /**
   * Returns the Observable object with the details of the clients retirieved from the API
   * @returns The clients from the API
   */
  getClientes() : Observable<Cliente[]> {
    return this.http.get<Cliente[]>(API_URL + clientes).pipe(catchError(err => this.handleError(err)));
  }

  /**
   * Creates a new client
   * @param cliente The new client
   * @returns The new client with the new id
   */
  createCliente(cliente) : Observable<Cliente>
  {
    return this.http.post<Cliente>(API_URL + clientes, cliente).pipe(catchError(err => this.handleError(err)));
  }

  /**
  * Returns the Observable object with the details of a client retrieved from the API
  * @returns The client details
  */
  getCliente(clienteId): Observable<Cliente> {
    return this.http.get<Cliente>(API_URL + clientes + '/' + clienteId).pipe(catchError(err => this.handleError(err)));
  }

  createTarjetaDeCredito(idCliente, tarjeta): Observable<TarjetaDeCredito> {
    return this.http.post<TarjetaDeCredito>(API_URL + clientes + '/' + idCliente + tarjetas, tarjeta);
  }

  /**
  * The method which handles the errors generated by the requests
  * @param error The error which the API REST returned
  */
  private handleError(error: any) { 
    return throwError(error.error.errorMessage);  
  }
}
